trigger:
- development

pool:
  name: BeePool

jobs:
  - job: PrepareEnvironment
    displayName: Prepare Environment
    steps:
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: LocalDirectory
          jdkFile: '../../../amazon-corretto-17-x64-linux-jdk.tar.gz'
          jdkDestinationDirectory: '../../../output'
          cleanDestinationDirectory: true
  - job: ExtractNameAndVersion
    displayName: Extract name and version
    dependsOn: PrepareEnvironment
    steps:
      - bash: |
          # Extract name and version while considering namespaces
          NAME=$(xmllint --xpath "string(//*[local-name()='name'])" pom.xml)
          VERSION=$(xmllint --xpath "string(//*[local-name()='version' and not(../parent)])" pom.xml)
          
          echo "##vso[task.setvariable variable=appName;isOutput=true]$NAME"
          echo "##vso[task.setvariable variable=appVersion;isOutput=true]$VERSION"
          
          echo "Project Name: $NAME"
          echo "Project Version: $VERSION"
        name: SetVariables
  - job: TestApplication
    displayName: Test Application
    dependsOn: ExtractNameAndVersion
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'pom.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.17'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          goals: 'test'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/target/surefire-reports'
          ArtifactName: 'test-report'
  - job: BuildApplication
    displayName: Build Spring Boot Application
    dependsOn: [TestApplication, ExtractNameAndVersion]
    variables:
      appName: $[ dependencies.ExtractNameAndVersion.outputs['SetVariables.appName'] ]
      appVersion: $[ dependencies.ExtractNameAndVersion.outputs['SetVariables.appVersion'] ]
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: 'package'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/target/$(appName)-$(appVersion).jar'
        ArtifactName: 'app'
