services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATA_SOURCE_URL=jdbc:postgresql://database:5432/root"
      - "SPRING_DATA_USERNAME=root"
      - "SPRING_DATA_PASSWORD=root"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "root"